FBU-2018-jalvarado/item-share-app

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.h, ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
began work on details page, pushing map implementation for rest of team to begin working on map connection.
=> Map and Details update

ItemShareApp/ItemShareApp/Models/Item.m, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.m
pushing so that nick can use it in his map stuff
=> passed item info to map

ItemShareApp/ItemShareApp/Models/MapModel.h, ItemShareApp/ItemShareApp/Models/MapModel.m, ItemShareApp/ItemShareApp/Models/SearchModel.h, ItemShareApp/ItemShareApp/Models/SearchModel.m, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
Updated MVC. Added search and map model classes.
=> MVC updated. Added map and search control models

ItemShareApp/ItemShareApp/Models/MapModel.h, ItemShareApp/ItemShareApp/Models/MapModel.m, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MapViewController.m
fixed MVC architecture. Map Model class is set and working.
=> new fixed updates to MVC architecture

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/CategoriesViewController.h, ItemShareApp/ItemShareApp/ViewControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PreviousViewController.h, ItemShareApp/ItemShareApp/ViewControllers/PreviousViewController.m, ItemShareApp/ItemShareApp/Views/CategoryViewCell.h, ItemShareApp/ItemShareApp/Views/CategoryViewCell.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
can go from category view to deeper levels or at lowest level it will default to the map
=> collection view separate from search is complete

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/CatAndItemTableViewController.h, ItemShareApp/ItemShareApp/ViewControllers/CatAndItemTableViewController.m, ItemShareApp/ItemShareApp/ViewControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.h, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PreviousViewController.m, ItemShareApp/ItemShareApp/Views/CategoryTableCell.h, ItemShareApp/ItemShareApp/Views/CategoryTableCell.m, ItemShareApp/ItemShareApp/Views/ItemTableCell.h, ItemShareApp/ItemShareApp/Views/ItemTableCell.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
the categories collection view on top of the searchView explores levels separately from the table view - now just have to set delegate to the placeholder view for the map segue
=> Search views

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BackgroundViewController.h, ItemShareApp/ItemShareApp/ViewControllers/BackgroundViewController.m, ItemShareApp/ItemShareApp/ViewControllers/CatAndItemTableViewController.m, ItemShareApp/ItemShareApp/ViewControllers/CategoriesViewController.h, ItemShareApp/ItemShareApp/ViewControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.h, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PreviousViewController.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
the delegates have all been set, the search view only covers part of the screen and it goes away at lowest level or on tapping map button now just need to animate the up and down dismissal and clean up the commented out code and like the segues to a map storyboard or the extra vc etc
=> Search holding view

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Storyboards/CalendarStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/CalendarViewController.m, ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.m
Can choose start and end date and transfers over to details view.
=> Calendar implementation finished

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Models/timeModel.h, ItemShareApp/ItemShareApp/Models/timeModel.m, ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.m
Booking implementation done. Need to polish UI. Bookings can be added to an item, and if a user selected time frame is booked, it will not book the item
=> Booking Times

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/MapStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/CatAndItemTableViewController.h, ItemShareApp/ItemShareApp/ViewControllers/CatAndItemTableViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.h, ItemShareApp/ItemShareApp/ViewControllers/PlaceholdViewController.m, ItemShareApp/ItemShareApp/ViewControllers/PreviousViewController.m, ItemShareApp/ItemShareApp/ViewControllers/SearchViewController.m
bug with categories not showing up initially is fixed and the tableview and category collection flow together, only one search bar, still need to make pins update with selection
=> Integrate search bar

ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.m
For when booking is not available
=> error message added

ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/Main/MapViewController.m, ItemShareApp/ItemShareApp/ViewControllers/Main/PlaceholdViewController.m
pins are adding back. Storyboards are connected
=> Map update

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/Main/PlaceholdViewController.m
If search bar has text, the category coll view disappears and the table view moves up and expands. If search bar doesn't have text then the categories reappear and the table view moves down and shrinks.
=> can table view's container view and actual table now move together

ItemShareApp/ItemShareApp/Models/Item.h, ItemShareApp/ItemShareApp/Models/Item.m, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/SellItemViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CatAndItemTableViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CatAndItemTableViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CategoriesViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/PlaceholdViewController.m
category collections and table view and search bar are all cohesive, so the map is the only thing left to connect
=> Integrate cat coll

ItemShareApp/ItemShareApp/Models/ColorScheme.h, ItemShareApp/ItemShareApp/Models/ColorScheme.m, ItemShareApp/ItemShareApp/PopUp/PopUpViewController.m, ItemShareApp/ItemShareApp/Storyboards/Base.lproj/LaunchScreen.storyboard, ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/CalendarViewController.m, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.h, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/MapViewController.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
color scheme model created. Color scheme can now be chosen and added in it
=> Color scheme model implemented

ItemShareApp/ItemShareApp/Info.plist, ItemShareApp/ItemShareApp/Storyboards/CalendarStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/CalendarViewController.m
=> calendar UI updates

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CatAndItemTableViewController.h, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CatAndItemTableViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/CategoriesViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/PlaceholdViewController.m
categories collection view can now scroll out of the search view
=> Categories scroll

ItemShareApp/ItemShareApp/Models/Item.h, ItemShareApp/ItemShareApp/Models/Item.m, ItemShareApp/ItemShareApp/Storyboards/SellItemStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/SellItemViewController.m
=> pictures are uploaded with the items

ItemShareApp/ItemShareApp/Storyboards/loginStoryboard.storyboard
=> registration updated

ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/SellItemStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m
image is loading in details view
=> picture is loading in details view

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ItemHistoryDetailViewController.h, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ItemHistoryDetailViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ItemHistoryViewController.h, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ItemHistoryViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ProfileDetailViewController.h, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ProfileDetailViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ProfileViewController.m, ItemShareApp/ItemShareApp/Views/ItemHistoryCell.h, ItemShareApp/ItemShareApp/Views/ItemHistoryCell.m, ItemShareApp/item-share-app.xcodeproj/project.pbxproj
profile exists, displays details of profile and items the user is selling
=> Profile detail

ItemShareApp/ItemShareApp/PopUp/PopUpViewController.h, ItemShareApp/ItemShareApp/PopUp/PopUpViewController.m, ItemShareApp/ItemShareApp/PopUp/PopUpViewController.xib, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.h, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/MapViewController.m
directions can be asked for in confirmed booking popup. This prints the directions on the map, but it is not interactive. Therefore, also implemented an option to open apple maps given the item address for more interactive experience. First implementation is commented out.
=> Directions

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/PlaceholdViewController.m, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/PreviousViewController.m, ItemShareApp/ItemShareApp/Views/CategoryViewCell.m
fixed table view bugs and the search bar always shows now
=> fixed tabel view bugs and the search bar always shows now

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/SellItemStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m
not rlly images selling - just the fixes that i wrote in the commit messages.
=> Images sell

ItemShareApp/ItemShareApp/Storyboards/loginStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/Login/RegisterViewController.m
did autocomplete functionality in register
=> Autocomplete

ItemShareApp/ItemShareApp/Models/Item.h, ItemShareApp/ItemShareApp/Models/Item.m, ItemShareApp/ItemShareApp/Models/MapModel.m, ItemShareApp/ItemShareApp/Models/myMarker.h, ItemShareApp/ItemShareApp/ViewControllers/MainControllers/MapViewController.m
Database changed. Added point key to item object, which stores the coordinate to the given address. Map now uses these stored coordinates rather than fetching them each time
=> map implementation changed.

ItemShareApp/ItemShareApp/Models/Category.m, ItemShareApp/ItemShareApp/Storyboards/Base.lproj/LaunchScreen.storyboard, ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/DetailsStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/QRCodeStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/loginStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/Login/LoginViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ItemHistoryDetailViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ProfileViewController.m, ItemShareApp/ItemShareApp/ViewControllers/QRViewController.m, ItemShareApp/ItemShareApp/Views/MGItemHistoryCell.h, ItemShareApp/ItemShareApp/Views/MGItemHistoryCell.m
* cut off decimal on total price 
* changed selling to post
* format address in detail, item history
* username should not be capital
* change names of categories
=> Small bugs

ItemShareApp/ItemShareApp/Storyboards/CategoriesStoryboard.storyboard, ItemShareApp/ItemShareApp/Storyboards/loginStoryboard.storyboard, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/DetailsViewController.m, ItemShareApp/ItemShareApp/ViewControllers/BookingControllers/SellItemViewController.m, ItemShareApp/ItemShareApp/ViewControllers/ProfileControllers/ProfileViewController.m
=> Pull to master
